tap "cjbassi/gotop"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
# Search tool like grep, but optimized for programmers
brew "ack"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Official Amazon AWS command-line interface
brew "awscli"
# Microsoft Azure CLI 2.0
brew "azure-cli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Programmable completion for Bash 4.2+
brew "bash-completion@2"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Statistics utility to count lines of code
brew "cloc"
# Configurable talking characters in ASCII art
brew "cowsay"
# Tool for exploring each layer in a docker image
brew "dive"
# Command-line tool to interact with exercism.io
brew "exercism"
# Extremely Fast Compression algorithm
brew "lz4"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Foreman in Go for Procfile-based application management
brew "forego"
# Infamous electronic fortune-cookie generator
brew "fortune"
# Search through your filesystem with SQL-esque queries
brew "fsql"
# GNU typing tutor
brew "gnu-typist"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# GNU grep, egrep and fgrep
brew "grep"
# HTTP load generator, ApacheBench (ab) replacement
brew "hey"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Command-line benchmarking tool
brew "hyperfine"
# Lightweight and flexible command-line JSON processor
brew "jq"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Fast, Dynamic Programming Language
brew "julia"
# Run local Kubernetes cluster in Docker
brew "kind"
# Curses-based tool for viewing and analyzing log files
brew "lnav"
# Rainbows and unicorns in your console!
brew "lolcat"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Java-based project management
brew "maven"
# Show markdown documents on text terminals
brew "mdcat"
# Modern and intuitive terminal-based text editor
brew "micro"
# Modern JVM-based framework for building modular microservices
brew "micronaut"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# DNS benchmark utility
brew "namebench"
# NCurses Disk Usage
brew "ncdu"
# Fast, highly customisable system info script
brew "neofetch"
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx", restart_service: true
# CLI for Postgres with auto-completion and syntax highlighting
brew "pgcli"
# Object-relational database system
brew "postgresql"
# Python version management
brew "pyenv"
# File browser
brew "ranger"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Proxy server that works as a poor man's VPN
brew "sshuttle"
# Cross-shell prompt for astronauts
brew "starship"
# Code-search similar to ack
brew "the_silver_searcher"
# Text interface for Git repositories
brew "tig"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Watch files and take action when they change
brew "watchman"
# Internet file retriever
brew "wget"
# HTTP benchmarking tool
brew "wrk"
# Download YouTube videos from the command-line
brew "youtube-dl"
# UNIX shell (command interpreter)
brew "zsh"
# Additional completion definitions for zsh
brew "zsh-completions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# A terminal based graphical activity monitor inspired by gtop and vtop
brew "cjbassi/gotop/gotop"
# JDK from the Java User Group (JUG)
cask "adoptopenjdk"
# AdoptOpenJDK OpenJDK (Java) Development Kit
cask "adoptopenjdk11"
# AdoptOpenJDK OpenJDK (Java) Development Kit
cask "adoptopenjdk8"
# Enable Windows-like alt-tab
cask "alt-tab"
# GUI app for Homebrew
cask "cakebrew"
# Sci-fi themed terminal emulator and system monitor
cask "edex-ui"
cask "font-fantasque-sans-mono"
cask "font-firacode-nerd-font"
cask "font-hack-nerd-font"
cask "font-hurmit-nerd-font"
cask "font-ibm-plex"
cask "font-iosevka-nerd-font"
cask "font-monofur-nerd-font"
cask "font-pt-mono"
cask "font-victor-mono"
# Development environment
cask "vagrant"
