prompt_order = [
    "username",
    "hostname",
    "time",
    "directory",
    "kubernetes",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "docker_context",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "erlang",
    "golang",
    "java",
    "julia",
    "nim",
    "nodejs",
    "ocaml",
    "php",
    "purescript",
    "python",
    "ruby",
    "rust",
    "terraform",
    "zig",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "custom",
    "line_break",
    "jobs",
    "battery",
    "character",
]

[character]
use_symbol_for_status = true 

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[docker_context]
disabled = true
only_with_files = true

[dotnet]
disabled = true

[elixir] 
disabled = true

[java]
style = "red"

[julia]
disabled = true

[kubernetes]
disabled = false

[nim]
disabled = true



