format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[docker_context]
disabled = true
only_with_files = true

[dotnet]
disabled = true

[elixir] 
disabled = true

[java]
style = "red"

[julia]
disabled = true

[kubernetes]
disabled = false

[nim]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[env_var]
variable = "MFA_PROMPT_INFO"
default = ""


